version: '3.7'

services:
  redis:
    image: redis:5.0-alpine
    command: redis-server --requirepass devpassword
    deploy:
      restart_policy:
        condition: none
    volumes:
      - redis:/data
    ports:
      - '6379:6379'


  pgdb:
    image: astrolabe/vosdb:latest
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  celery:
    image: astrolabe/cuts:latest
    command: celery worker -l debug -A cuts.blueprints.img.tasks
    deploy:
      restart_policy:
        condition: none
    depends_on:
      - redis


  dals:
    image: astrolabe/dals:1H
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./images:/vos/images
    ports:
      - "8080:8080"
    depends_on:
      - pgdb


  cuts:
    image: astrolabe/cuts:latest
    deploy:
      restart_policy:
        condition: none
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - './images:/vos/images:ro'
    ports:
      - '8000:8000'
    depends_on:
      - celery


networks:
  default:
    name: vos_net
    attachable: true

volumes:
  pgdata:
  redis:
