version: "3.7"

services:
  redis:
    image: redis:5.0-alpine
    command: redis-server --requirepass devpassword
    deploy:
      restart_policy:
        condition: none
    volumes:
      - redis:/data
    ports:
      - "6379:6379"


  pgdb:
    image: vosdb:devel
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  celery:
    image: cuts:devel
    command: celery worker -l debug -A cuts.blueprints.img.tasks
    deploy:
      restart_policy:
        condition: none
    depends_on:
      - redis


  dals:
    image: dals:devel
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./images:/vos/images
    ports:
      - "8080:8080"
    depends_on:
      - pgdb
      - nginx


  cuts:
    image: cuts:devel
    deploy:
      restart_policy:
        condition: none
    environment:
      PYTHONUNBUFFERED: "true"
    volumes:
      - ./images:/vos/images:ro
    ports:
      - "8000:8000"
    depends_on:
      - celery
      - nginx


  nginx:
    image: nginx:1.17.9
    deploy:
      restart_policy:
        condition: none
    environment:
#      - NGINX_HOST=hector.cyverse.org
      - NGINX_HOST=esne
      - NGINX_PORT=80
    volumes:
      - /vos/config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
#      - 443:443
    networks:
      - vos_net
      - default


networks:
  vos_net:
    name: vos_net
    attachable: true

volumes:
  pgdata:
  redis:
